### ISSUE TITLE
TFLite fails to build in the Docker container

### ISSUE THREAD

**Issue by RaphaelRoyerRivard** [Volcomix/virtual-background#1]
Hi, I am trying to run your demo on my Mac and when I run `yarn build:tflite:all` and bazel tries to build tflite, it fails with this error :
```
$ docker exec -w /tflite_src tflite bazel build --config=wasm -c opt :tflite
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
ERROR: error loading package '': cannot load '@org_tensorflow//tensorflow:workspace.bzl': no such file
INFO: Elapsed time: 4.869s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I would guess I have to change something in the `/tflite_src/WORKSPACE` file but I don't know how bazel works yet. I will try to fix the issue and will comment again if I find how to get rid of the error.

**Comment by Volcomix** [comment]
Hi @RaphaelRoyerRivard, thanks for reporting that. I juste took a look at tensorflow repo and it looks like `tensorflow/workspace.bzl` is gone from the master branch.
I'll investigate as soon as possible (most probably this weekend) to figure out how it has been replaced.

As a workaround, maybe could you try checking out the tag v2.4.1 of tensorflow within the container, manually apply the seds from the dockerfile and try again.
I don't have a computer so I can't be more specific right now but I will come back to you as soon as possible.

**Comment by RaphaelRoyerRivard** [comment]
Thanks a lot for your answer, I will try that.

**Comment by RaphaelRoyerRivard** [comment]
I deleted the container and replaced the following line in Dockerfile
```
RUN git -C /tensorflow_src pull
```
with
```
RUN git -C /tensorflow_src fetch
RUN git -C /tensorflow_src checkout 85c8b2a817f95a3e979ecd1ed95bff1dc1335cff
```
which is the 2.4.1 tag of Tensorflow and it built successfully :)

**Comment by Volcomix** [comment]
Nice thank you for the feedback!

**Comment by Volcomix** [comment]
3d1593d should fix the issue.

Let me know if you still have troubles to build TFLite (if you decide to switch back to tensorflow master :wink:).
