### ISSUE TITLE
BodyPix tflite model support

### ISSUE THREAD

**Issue by charliesantos** [Volcomix/virtual-background#11]
@Volcomix , your work is really impressive! Thank you so much for this work.

I saw this comment from @PINTO0309 in this issue https://github.com/Volcomix/virtual-background/issues/2#issuecomment-829730723
> I don't know if it will be useful for you, but I have converted and quantized it for various frameworks and committed it to my repository.
> 
> **TFLite Float32/Float16/INT8, TFJS, TF-TRT, ONNX, CoreML, OpenVINO IR FP32/FP16, Myriad Inference Blob**
> 
> https://github.com/PINTO0309/PINTO_model_zoo
> https://github.com/PINTO0309/PINTO_model_zoo/tree/main/109_Selfie_Segmentation

And I'm able to easily play with the different models. Thank you both for your hardwork.

I noticed @PINTO0309 also has bodypix tflite models [here](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/035_BodyPix) but they don't seem to work with @Volcomix pipeline. Getting some logs I noticed the output image has the following:
```js
console.log({
  inputHeight: this._tflite._getInputHeight(),
  inputWidth: this._tflite._getInputWidth(),
  inputChannelCount: this._tflite._getInputChannelCount(),
  outputHeight: this._tflite._getOutputHeight(),
  outputWidth: this._tflite._getOutputWidth(),
  outputChannelCount: this._tflite._getOutputChannelCount(),
});
// Outputs an image with 10x8 resolution, 17 channels
```

As you can see, the output seems wrong. Any advice on what to adjust? My intention is I want to run bodypix model in wasm hoping to gain more performance than the tfjs one. Is this something you can help with? Thank you in advance!

**Comment by Volcomix** [comment]
Hey @charliesantos, thanks for reaching out. Indeed @PINTO0309 is doing an awesome work on these model conversions!
BodyPix models won't work with the pipelines of this demo without some tweaks. Especially because of the output which need to be decoded:
* https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/single_person/decode_single_pose.ts
* https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/single_person/util.ts

Not sure how easy it would be, I'll try to investigate a little bit.

**Comment by charliesantos** [comment]
Thank you @Volcomix . It would be nice to at least use bodypix in wasm for the virtual background use case like the ones you have in this repo for google meet, ML Kit, and bodypix tfjs. No need to detect different poses.

**Comment by Volcomix** [comment]
I [created a branch](https://github.com/Volcomix/virtual-background/tree/bodypix-tflite) to experiment on BodyPix tflite models. I understand that the 4th output is supposed to hold the segmentation but I don't really understand how to work with its 20x15 resolution, even after looking into TF.js source code.
Any hint from @PINTO0309 maybe? Did you get any working example in Python with the float16 quantized model?

![image](https://user-images.githubusercontent.com/7324857/119266735-3a511380-bbec-11eb-9d5a-cd78de508ba8.png)

The inference time is good but I guess this one is for the worst accuracy. Not sure how promising it is. The output is unusable for now:
![image](https://user-images.githubusercontent.com/7324857/119266815-88fead80-bbec-11eb-8ed6-a9d8365b5a46.png)

I'm not sure I will invest a lot more time on it so any help would be welcome.

**Comment by PINTO0309** [comment]
I have not written any sample code, but the following repository may be helpful.
https://github.com/hegman12/body_pix_tflite

The last time I converted the model was a long time ago (about a year ago), so I will try to convert it again with the latest knowledge.

**Comment by Volcomix** [comment]
Awesome! Thanks for the update I'm gonna take a look.

**Comment by PINTO0309** [comment]
@Volcomix 
The conversion took only five minutes. But what kind of resolution model do you want? I can change it as much as I want. The figure below shows the MobileNetV2 240x320 resolution model.
![Screenshot 2021-05-24 11:39:32](https://user-images.githubusercontent.com/33194443/119289300-4b019800-bc85-11eb-8450-d21ea0747dcf.png)

**Comment by PINTO0309** [comment]
All the models were re-transformed and totally replaced with the same model structure of TensorFlow.js.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/035_BodyPix**

**Comment by charliesantos** [comment]
Thank you @PINTO0309 @Volcomix you both are amazing!

**Comment by PINTO0309** [comment]
I found a better sample.
**https://github.com/google-coral/project-bodypix**
![segmentation](https://user-images.githubusercontent.com/33194443/119413219-2c081200-bd28-11eb-87f8-8d6a43aa8635.gif)

**Comment by PINTO0309** [comment]
Here is the one that was easiest to understand.
**https://github.com/de-code/python-tf-bodypix**

**Comment by Volcomix** [comment]
Thank you so much @PINTO0309. I can see that the new model output still has a resolution of 15x20 so I need to figure out how to map this on a 240x320 image. Hopefully I'll find the answer in the samples you found for us 🤞.
I'm gonna be pretty busy during the week so please don't worry if I answer with a little bit of delay.

**Comment by Volcomix** [comment]
After loading the new tflite models and trying with the fastest one (mobilenet050, stride16, 240x320, float16 quantization), the performance seems equivalent/worse with tflite on wasm than with tfjs on webgl. Moreover the tfjs one works on a higher resolution:

![image](https://user-images.githubusercontent.com/7324857/120098221-e3d85d80-c134-11eb-81b1-8715d147463e.png)

![image](https://user-images.githubusercontent.com/7324857/120098238-f9e61e00-c134-11eb-997a-9983d0b3b419.png)

After checking other projects code and the tfjs implementation of BodyPix more closely, I would have to handle padding and scaling implied by the strides which is implemented using tensorflow in all the reference projects but would required a lot of extra work in this demo. As the performance result are not that good with the tflite model of BodyPix, I don't wish to invest more time on this specific experiment.

I'm very sorry PINTO for making you spend time on it without ending.

P.S.: There is a work in progress in TF.js to handle tflite models. Maybe is there a chance that BodyPix would work on it when it will be ready: https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite

**Comment by cansik** [comment]
@Volcomix I am currently playing around with the openvino model provided by @PINTO0309 and I am was able to detect the keypoints of a person. However, the `float_segments` seem to be off by some pixels (or scale), if I resize them to the actual image size. How did you convert the mask from the `segments` to match the actual image size?

<img width="507" alt="image" src="https://github.com/Volcomix/virtual-background/assets/5220162/40ce3c0d-82fa-4ffd-a15c-6b20b3b4835b">
