### ISSUE TITLE
Regression: SIMD support

### ISSUE THREAD

**Issue by jiangts** [Volcomix/virtual-background#12]
Thanks for sharing this amazing project!

I just noticed that SIMD support seems to be broken now. See this `console.warn` messages
![image](https://user-images.githubusercontent.com/4052045/119035571-8e49c700-b964-11eb-847d-e645bee175e6.png)

Not sure if this is related to recent commits updating the tflite version numbers?

**Comment by jiangts** [comment]
oh, wait is this a flag that needs to be enabled on the browser side? The SIMD option was available for me on your demo site yesterday, but disappeared today! Very weird...

**Comment by Volcomix** [comment]
Hi @jiangts, thanks a lot for reporting this issue. Indeed Chrome origin trial expired yesterday (May the 19th). I renewed the origin trial in ebf239f55ede070a55b76b86dd667b518dccf448 to fix the issue. SIMD should be back!

**Comment by jiangts** [comment]
Wow, you are amazing! Very impressed that you were able to compile tflite to wasm and load these models. I got a bit into emscripten compilation learning from https://github.com/ffmpegwasm/ffmpeg.wasm and I've learned a bit more from this repo (not so familiar with `bazel` yet though).

**Comment by Volcomix** [comment]
Thanks a lot, I'm glad that you found this project useful!
Learning bazel is not very smooth and I also struggled a little bit in the beginning. Building tflite was also tricky, especially because some key configurations are kind of hidden and are kept outside of tensorflow repos. Happy to share them!
