### ISSUE TITLE
Green screen integration 

### ISSUE THREAD

**Issue by drenmullafetahu** [Volcomix/virtual-background#14]
Is there in plan to add a green screen integration with webgl ?

Thank you.

**Comment by Volcomix** [comment]
I'm not sure what would be the goal of handling green screens. The purpose of this demo is to show that we can replace the background without relying on physical backdrop. So basically if you have a green screen, it should work with this demo out of the box.
If what you have in mind is rather to replace the background with green pixels, this could be done easily by using a green background image or by replacing the background replacement shader with one that just put green pixels instead. I don't plan to add this feature in the demo as I don't see any use case where putting green pixels would be the real end goal.
