### ISSUE TITLE
Can't resolve 'fs' and 'path'

### ISSUE THREAD

**Issue by benbro** [Volcomix/virtual-background#15]
I'm trying to add the virtual background to an angular 11 app. When calling 'ng serve' I'm getting the following errors:
```bash
Error: ./src/tflite/tflite.js
Module not found: Error: Can't resolve 'fs' in 'src/tflite'

Error: ./src/tflite/tflite.js
Module not found: Error: Can't resolve 'path' in 'src/tflite'
```
Adding this to package.json resolve the issue. Is there a way to fix the errors without changing package.json or other config files?
```json
"browser": {
    "fs": false,
    "path": false
},

**Comment by Volcomix** [comment]
I think you could try to set a specific [target environment](https://github.com/emscripten-core/emscripten/blob/087ca39beeb6203ac838925f4a3e9c67623fb2fc/src/settings.js#L626) in [`BUILD`](https://github.com/Volcomix/virtual-background/blob/main/tflite/BUILD) file:
```
-s ENVIRONMENT='web'
```

**Comment by benbro** [comment]
I'll try to build the model with the ENVIRONMENT. Shouldn't it be the default from this project?

**Comment by Volcomix** [comment]
Could be the default indeed, it would probably reduce the js file size.

**Comment by benbro** [comment]
Works great. Thanks
