### ISSUE TITLE
Wrong path for tflite.wasm

### ISSUE THREAD

**Issue by benbro** [Volcomix/virtual-background#16]
I'm trying to add the virtual background to an angular 11 project and getting an error when trying to load the tflite model:

```
GET http://localhost:4200/tflite.wasm 404 (Not Found)
tflite.js:9 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': HTTP status code is not ok
tflite.js:9 falling back to ArrayBuffer instantiation
GET http://localhost:4200/tflite.wasm 404 (Not Found)
failed to asynchronously prepare wasm: RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.
```

This is how I import tflite.js:
```javascript
import createTFLiteModule from './tflite/tflite';
import createTFLiteSIMDModule from './tflite/tflite-simd';
```

The path to tflite.wasm is hardcoded in tflite/tflite.js. Is there a config option to set the path without modifying tflite.js?
```javascript
var wasmBinaryFile="tflite.wasm"
```

**Comment by Volcomix** [comment]
I hope there is a way to import wasm module using ES modules like you did but I haven't found the right way to do it. So what I did in this demo was to put `tflite.js` and `tflite.wasm` in the public directory (aka `assets` in Angular), manually added the required `<script>` tags in [`index.html`](https://github.com/Volcomix/virtual-background/blob/c367b96ba0fc2213a9ff262dde06e352754b5288/public/index.html#L46) and manually declared [`createTFLiteModule`](https://github.com/Volcomix/virtual-background/blob/c367b96ba0fc2213a9ff262dde06e352754b5288/src/core/hooks/useTFLite.ts#L7) for TypeScript to be happy when calling it without any associated `import`.

**Comment by benbro** [comment]
I didn't find a way to set the path yet. Maybe we can add a global variable like TFLITE_URL and TFLITE_SIMD_URL that the js file will use if exists. Not sure if relevant.

**Comment by Volcomix** [comment]
Actually `tflite.js` and `tflite.wasm` are generated by [emscripten](https://emscripten.org/) and the glue code in the js file is overwritten each time I build tflite in wasm. I don't think that would be a good idea to edit the file manually so unless there is an existing option in emscripten to specify the wasm file URL (which I can't find), I don't see any other alternative than importing those file from outside of the bundled code.

**Comment by benbro** [comment]
Relative path should work if loading tflite.js in a script tag because the glue code use document.currentScript.url. See https://github.com/emscripten-core/emscripten/pull/5368
```
var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
```
Angular dev server generate the html dynamically with <script src="app.js"></script>. That's why document.currentScript.url points to the root path.
I think on dev we can add a proxy that handles the wasm files specifically. Maybe with "ng serve --proxy-config proxy.conf.json".
On production, as long as the .js and wasm files will be in the same path it should work because of document.currentScript.url.

**Comment by benbro** [comment]
Maybe we need
```
-s EXPORT_ES6=1 will turn the JavaScript code into an ES6 module with a default export that works with any bundler. Also requires -s MODULARIZE=1 to be set.
```

**Comment by Volcomix** [comment]
Running a build with this option (https://github.com/Volcomix/virtual-background/commit/cdad50c0f67c3537854c1b9ea6b8bef498b55fcc): https://github.com/Volcomix/virtual-background/actions/runs/890576517

**Comment by benbro** [comment]
There is also [USE_ES6_IMPORT_META=1](https://github.com/emscripten-core/emscripten/blob/main/src/settings.js#L1166):

// Use the ES6 Module relative import feature 'import.meta.url'
// to auto-detect WASM Module path.
// It might not be supported on old browsers / toolchains
var USE_ES6_IMPORT_META = 1;

**Comment by Volcomix** [comment]
I updated tflite js files in [this branch](https://github.com/Volcomix/virtual-background/tree/emscripten-es6-export). React is yelling at me when trying to import them as ES6 modules:
![image](https://user-images.githubusercontent.com/7324857/120114117-ead78e00-c17d-11eb-9163-4db3e29a0313.png)

But maybe could you have more luck with Angular.

USE_ES6_IMPORT_META is enabled by default so I'm gonna run a new build with this option disabled.

**Comment by benbro** [comment]
I'm getting a similar error with Angular 11. EXPORT_ES6=1 with import.model.url is probably the solution but react and angular tooling are not compatible with import.model yet.

**Comment by benbro** [comment]
I still prefer the automatic import.model.url solution but we can also pass custom locateFile function:
```javascript
const createdTFLiteSIMD = await createTFLiteModule({locateFile: () => 'path/to//tflite.wasm'});
```

**Comment by Volcomix** [comment]
Still an error with `"-s USE_ES6_IMPORT_META=0"`:

![image](https://user-images.githubusercontent.com/7324857/121773236-ce265780-cb7a-11eb-813e-1f61045b2b27.png)

**Comment by benbro** [comment]
Not sure about complication flags but we can use locateFile  to dynamically specify the model location.
This is from the [Selfie Segmentation example](https://google.github.io/mediapipe/solutions/selfie_segmentation#javascript-solution-api):
```javascript
const selfieSegmentation = new SelfieSegmentation({locateFile: (file) => {
  return `https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation/${file}`;
}});
```
