### ISSUE TITLE
Check if simd is supported

### ISSUE THREAD

**Issue by benbro** [Volcomix/virtual-background#18]
A function that check if simd is supported. Based on [wasm-check](https://github.com/MaxGraey/wasm-check/blob/master/lib/index.js).

Can be used [here](https://github.com/Volcomix/virtual-background/blob/main/src/core/hooks/useTFLite.ts#L31) instead of try/catch.

```javascript
private simdSupported(): boolean {
  const u32 = (...bytes: number[]) => Uint32Array.of(0x6D736100, 1, ...bytes);
  const u32a = (...bytes: number[]) => u32(1610679297, 33751040, ...bytes, 40239360, 259);

  let wasm = u32a(84344833, 6357249, 17369600, 4259847, 186257917, 1845758464);
  const buffer = wasm.buffer;
  if (WebAssembly.validate(buffer)) {
    try {
      new WebAssembly.Instance(new WebAssembly.Module(buffer)).exports['0']();
      return true;
    }
    catch (_a) {
      return false;
    }
  }
  return false;
}
```

**Comment by Volcomix** [comment]
Thanks for pointing this out. There is also the one from [GoogleChromeLabs](https://github.com/GoogleChromeLabs/wasm-feature-detect) which looks great.

[TF.js](https://github.com/tensorflow/tfjs/blob/e642f856dd289088610378d5042f19dc54c05601/tfjs-backend-wasm/src/flags_wasm.ts#L30) is using a copy of it:
```ts
WebAssembly.validate(new Uint8Array([
  0, 97, 115, 109, 1, 0, 0, 0, 1,  4, 1,   96, 0,  0, 3,
  2, 1,  0,   10,  9, 1, 7, 0, 65, 0, 253, 15, 26, 11
]))
```

**Comment by benbro** [comment]
This looks cleaner. I'll update my code. Thanks.
