### ISSUE TITLE
Change blur intensity in the WebGL2 pipeline

### ISSUE THREAD

**Issue by benbro** [Volcomix/virtual-background#19]
How can I decrease the blur intensity in the WebGL2 pipeline? Even manually by changing the code.Non of the controls in the demo seems to affect it.

What does the coverage parameter do? It seems the only parameter passed to BackgroundBlurStage but I don't see any effect in the result when changing it.

**Comment by Volcomix** [comment]
There is currently no control to change the blur intensity. You can change it by editing any (or both) of these lines:
* [Number of blur passes](https://github.com/Volcomix/virtual-background/blob/021e3d8701480648d638e9074d2f77ae362cb6d9/src/pipelines/webgl2/backgroundBlurStage.ts#L166)
* [Input image scale for linear sampling](https://github.com/Volcomix/virtual-background/blob/021e3d8701480648d638e9074d2f77ae362cb6d9/src/pipelines/webgl2/backgroundBlurStage.ts#L98)

The coverage parameter allows us to control the transition between the background and the foreground by changing the left edge and right edge of the [smoothstep function](https://en.wikipedia.org/wiki/Smoothstep).

**Comment by benbro** [comment]
Thank you for the explanation.

Do you use separable filters for the weighted blur?
Do you change the weight based on the circle-of-confusion (CoC) radii like in the [Google Meet blog](https://ai.googleblog.com/2020/10/background-features-in-google-meet.html)?
I'm new to shaders and the algorithms and trying keep track.

**Comment by Volcomix** [comment]
I do use separable filter. The vertical pass is [here](https://github.com/Volcomix/virtual-background/blob/021e3d8701480648d638e9074d2f77ae362cb6d9/src/pipelines/webgl2/backgroundBlurStage.ts#L169) and horizontal pass [here](https://github.com/Volcomix/virtual-background/blob/021e3d8701480648d638e9074d2f77ae362cb6d9/src/pipelines/webgl2/backgroundBlurStage.ts#L177). You can find some explanation in [this article](https://software.intel.com/content/www/us/en/develop/blogs/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms.html).

I'm changing the weight based on the segmentation values (you can find an example [here](https://github.com/Volcomix/virtual-background/blob/021e3d8701480648d638e9074d2f77ae362cb6d9/src/pipelines/webgl2/backgroundBlurStage.ts#L88)). This avoids the person pixels to be blurred along with the background ones but I didn't really understand if this is what Google described in their blog when mentioning the CoC or if we could apply an additional effect :shrug:.

**Comment by benbro** [comment]
Thanks
