### ISSUE TITLE
Demo not running on Safari 14.1.12

### ISSUE THREAD

**Issue by slpn1** [Volcomix/virtual-background#26]
Page starts to load UI then blanks.

Error in the console is: TypeError: null is not an object (evaluating 'm.VERTEX_SHADER')

**Comment by Volcomix** [comment]
Hi @slpn1,

Indeed this demo relies on WebGL 2.0 which is supported on Safari 14.1 only after enabling it in the "Experimental Features" developer menu.

It is supported by default starting from Safari 15 (https://caniuse.com/webgl2).
