### ISSUE TITLE
How to make it work in synchronous mode - wegGL2 

### ISSUE THREAD

**Issue by yxt132** [Volcomix/virtual-background#36]
this is outstanding work and cudos to OP! I wonder how we can make this work in synchronous mode, rather than asynchronous mode. I am pretty new to webgl stuff. Any insight will be greatly appreciated!

**Comment by Volcomix** [comment]
Thanks! I think you only need to replace this line: https://github.com/Volcomix/virtual-background/blob/674aee05879e993189ccd12b439cf08b2221a80e/src/pipelines/webgl2/resizingStage.ts#L81
with:
```ts
gl.readPixels(
```

Here is the commit that introduced the async pixel download: https://github.com/Volcomix/virtual-background/commit/ccf69fc31a8a9494b7e9067ebb50a50fe7801615

**Comment by yxt132** [comment]
Thanks for your speedy response. I will give it a try!

**Comment by yxt132** [comment]
It works like a charm. Thank you, OP! You can close this issue now.
