### ISSUE TITLE
some question about device

### ISSUE THREAD

**Issue by FengMu1995** [Volcomix/virtual-background#45]
Hi, thanks for your excellent job. The web virtual-background is running only with user ? no server, no extra gpu?

**Comment by Volcomix** [comment]
Hi, this demo is a web app and needs to run within a web browser compatible with WebGL 2, on a machine with GPU.
The web browser could eventually run on a server with extra GPU but I'm not sure this would be the most efficient way to compute background segmentation on server side.

**Comment by FengMu1995** [comment]
ok, thanks
