### ISSUE TITLE
Mediapipe webassembly

### ISSUE THREAD

**Issue by hongs202010** [Volcomix/virtual-background#6]
First of all thank you for the efforts you put on to this project. I have gained insights on Tflite-wasm-simd from your project.
I am aware that this question might not be totally relevant to this project, but have you ever tried compiling Mediapipe to WASM from their entire source?

**Comment by Volcomix** [comment]
Thank you for encouraging this work, I'm glad to hear the project was useful to you. I haven't tried compiling Mediapipe to WASM but that could be an interesting challenge.

Not sure I would be able to try it anytime soon but I'll keep the issue open to take a look in the coming weeks.

**Comment by Volcomix** [comment]
I'm closing the issue because I don't think I'll work on it anytime soon and if I do, it would be in another project. Thanks.
