### ISSUE TITLE
Feature Request for Face Skin Smoothing

### ISSUE THREAD

**Issue by dominicklee** [Volcomix/virtual-background#7]
Hi @Volcomix, thank you for the amazing work! By any chance, have you considered applying "Beauty Filter" or some sort of "face recognition skin smoothing" filter for this? To mainly remove blemishes

Please let me know if you know of any web-based solution to achieve it. Face enhancement is important for some of our users.

Thanks again!

**Comment by Volcomix** [comment]
Hi @dominicklee, thank you for the kind words. I don't know any existing web-based solution for such processing and I don't know any skin segmentation model neither.
However if you manage to find a good quality skin segmentation model which takes care of tricky regions like the mouth and the eyes, we should be able to apply the technics implemented in this repo to perform smoothing post-processing on the segmented parts of the image.
