### ISSUE TITLE
Incorrect response MIME type. Expected 'application/wasm'

### ISSUE THREAD

**Issue by drlight17** [Volcomix/virtual-background#9]
Hello.
Nice work of yours! I've used some of your code in [my demo](https://github.com/drlight17/background-process-demo) in research purposes. Tested it and your demo on my old Linux Mint notebook and these errors appear when webgl processing is trying to start:
`wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`
and then as a result:
`Uncaught (in promise) TypeError: Cannot read property 'VERTEX_SHADER' of null`
OS is:
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
```
Browser is:
```
# apt show chromium-browser
Package: chromium-browser
Version: 90.0.4430.93-0ubuntu0.18.04.1
```
chrome://gpu contains:
```
Graphics Feature Status
Canvas: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Disabled
Out-of-process Rasterization: Hardware accelerated
OpenGL: Enabled
Rasterization: Hardware accelerated on all pages
Skia Renderer: Enabled
Video Decode: Hardware accelerated
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
```
Does my notebook have some hw or sw incompatibles with wasm?
Thanks.

**Comment by Volcomix** [comment]
Hello @drlight17 and thanks!
Are you serving the app with create-react-app dev server (aka webpack-dev-server)? This should be the case if you run `yarn start` with this demo project.
The dev server is supposed to set the right MIME type for wasm files in response headers. If you are using another web server, I guess there are some config to add.

Otherwise, this error can also happen when the wasm file is not found by the dev server, in which case it returns the `index.html` file instead (which obviously won't have the wasm MIME type).

**Comment by drlight17** [comment]
> Hello @drlight17 and thanks!
> Are you serving the app with create-react-app dev server (aka webpack-dev-server)? This should be the case if you run `yarn start` with this demo project.
No, I try to open your hosted demo at the link https://volcomix.github.io/virtual-background/
> The dev server is supposed to set the right MIME type for wasm files in response headers. If you are using another web server, I guess there are some config to add.
> 
> Otherwise, this error can also happen when the wasm file is not found by the dev server, in which case it returns the `index.html` file instead (which obviously won't have the wasm MIME type). Have you checked the response body in the network tab of your browser devtools?
No, but I'll check and tell you a little later.

**Comment by drlight17** [comment]
I've checked network tab, see screenshot:
![image](https://user-images.githubusercontent.com/37434652/118232538-64426180-b499-11eb-90ce-a666c2d85705.png)

Something is really wrong. What is the "bad magic number"?

**Comment by Volcomix** [comment]
Looks like this is the expected response when opening wasm file in this tab. So I guess you received the right file.
Would you mind sharing also a screenshot of the response headers along with an extract of your browser console?

**Comment by jiangts** [comment]
A lot of static file servers don't yet recognize the `.wasm` extension, so you need to give them a bit of help.

If using `express` on Node.js, just add this line:

```
express.static.mime.define({'application/wasm': ['wasm']});
```

**Comment by Volcomix** [comment]
I don't see anything wrong with your hardware or software @drlight17. I tried installing Chromium to check potential incompatibilities and both wasm and SIMD seem working. Chromium version was 91 though. Maybe you could try updating yours but I don't have other ideas for now.

Unless you have more insights regarding response headers and error details from the browser console, I'm gonna close the issue. Thanks.

![image](https://user-images.githubusercontent.com/7324857/120064469-9abcd680-c06c-11eb-9705-cd76e9d04fbd.png)
